---
- name: Check support for OS family
  fail: msg="Distro {{ ansible_distribution }} not supported"
  when: ansible_os_family not in ['Debian', 'RedHat']

- include: Debian-repository.yml
  when: ansible_os_family == 'Debian'
  tags: [repository,rabbitmq]

- include: Debian-install.yml
  when: ansible_os_family == 'Debian'
  tags: [repository,rabbitmq]

- include: RedHat-repository.yml
  when: ansible_os_family == 'RedHat'
  tags: [repository,rabbitmq]

- include: RedHat-install.yml
  when: ansible_os_family == 'RedHat'
  tags: [packages,rabbitmq]

- include: config-cluster.yml
  when: rabbitmq_create_cluster

- include: config.yml

- include: service.yml

- include: cluster.yml
  when: 'rabbitmq_create_cluster and (ansible_hostname != rabbitmq_cluster_master)'

- include: rabbitmq.yml
  when: 'not rabbitmq_create_cluster or (ansible_hostname == rabbitmq_cluster_master)'

- meta: flush_handlers
